version: '3.8'

services:
  backend:
    image: node:slim
    command: sh -c 'npm install && npm run generate-docs && npm run dev'
    volumes:
      - .:/api
    working_dir: /api
    ports:
      - "127.0.0.1:95:95"
    restart: always