services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    image: node:slim
    command: sh -c 'npm install && npp run start'
    volumes:
      - .:/api
    working_dir: /api
    ports:
      - "127.0.0.1:95:95"
    restart: always

volumes:
  db_data:
