version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_bridge_network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_bridge_network

  backend:
    image: node:slim
    command: sh -c 'npm install && npm run dev'
    volumes:
      - .:/api
    working_dir: /api
    ports:
      - "127.0.0.1:95:95"
    restart: always
    networks:
      - my_bridge_network

volumes:
  db_data:

networks:
  my_bridge_network:
    driver: bridge
