name: Deploy Vue.js Frontend and Node.js Backend

on:
  push:
    branches:
      - deploiment-ci-cd

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      ### --- BUILD DU FRONTEND ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and build frontend
        working-directory: ./ws-cinema
        run: |
          npm install
          npm run build

      - name: Deploy frontend to server
        uses: appleboy/scp-action@v0.2.4
        with:
          host: ${{ secrets.HOSTNAME }}
          username: your-username
          password: ${{ secrets.PASSWORD }}
          source: ./ws-cinema/dist/*
          target: ${{ secrets.FRONT_PATH }}